version: "3.9"
name: "cyberzone-frontend"

services:  
  frontend:
    container_name: "cyberzone-frontend"
    image: "registry.cyberzone.dev/website/frontend:latest"
    restart: always
    env_file:
      - stack.env
    ports:
      - "3000:80"